
multiple:
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/master?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
      username: root
      password :
    slave1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/salve_first?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
      username: root
      password :
    slave2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/salve_first?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
      username: root
      password :
    slave3:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/salve_first?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
      username: root
      password :
    other:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/salve_first?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
      username: root
      password :

server:
  port: 8088
mybatis:
  mapper-locations: classpath:mapper/*.xml

