


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quick_start?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.kk.mybatis.plus: debug

mybatis-plus:
  # ??? mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml

server:
  port: 8081